dist: trusty
sudo: false
language: go
go:
- 1.x
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
- DEP_VERSION="0.5.0"
before_install:
- curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64
  -o $GOPATH/bin/dep
- chmod +x $GOPATH/bin/dep
install:
- dep ensure
- make all
deploy:
  provider: releases
  api_key:
    secure: bk0TK3VK3Vp0CIQR2DRDBhY8vhEuC44mh2Ar2WLkG0tW10nxccBwo4HA4SuflWJ7Gch2JEST5+BtNGREzBf9WHsAGRxLgqs3QyF2umQr0G+qhdou1yt+zgO69yLzn8fNUrT+klWEAtbnRH1ODKnN+Y9pgpZXGX9H7j8Y2P7SwIL5PNr5EU+kowI8Dk62dkdX9lSXnyiWZ0Qb8zeptMfFIiyN4/DZSSt36Lk+aJX9tl2ldvNdcaRF2Qxx8GviTR8YUhTWlFWSyZSiaNIb/oDf6cCHnsJOGhllfOcgRFEIo4tG+mJpD28uMLx330qc/3JIKYEBtfpwnUDoZeB+Dt7ruz7W/jgLefvu8Nzg5NBFz4ELeged6QL43IBhVaAbjk3I91r/wSLxZ+8turkRilF4VAxdylzYqsL/EtOZuHKRJokutgGrdLHgPqjppq9kkMzgfw/a6GUuaRQmLUrFb8SolOXHeNNXeoD6FBmKZZYgneCIt+dG7WYFrYYPDpT/BYE3g07FsHTjD/zNJAPvSJxZV4n13KGAsVQmM7ZHXk5n18UqRMMn9LaFXpJyFW9OBpjLS3Ma8rlSwe4ZRgFi9Z3diAb0jopiNngamdQG+fJqAbFGp+6m0QiR3fV/41/IGmEHkUKYK04AD0pMApShWYkwk4X9K2sDOQuh/jGK0HqgyNI=
  file: dist/*
  file_glob: true
  skip_cleanup: true
  on:
    repo: moussetc/mattermost-plugin-dice-roller
    tags: true
